#
# WebSVN (sshd DEBUG) Docker container
#
# Version 0.0

FROM debian:8
MAINTAINER Joseph Lutz <Joseph.Lutz@novatechweb.com>

# create the volumes that will be needed
VOLUME ["/etc/apache2/ssl/"]

CMD ["true"]
