BACKUP_DIR=$(pwd)/BACKUP

TAG="current"
CONTAINER_ENDING=""
#CONTAINER_ENDING="_${TAG}"
{ # variables for OpenSSL
  NAME_OPENSSL_IMAGE="novatechweb/data_openssl"
  NAME_OPENSSL_DV="DV_openssl${CONTAINER_ENDING}"
}

{ # variables for htpasswd
  NAME_HTPASSWD_IMAGE="novatechweb/data_htpasswd"
  NAME_HTPASSWD_DV="DV_htpasswd${CONTAINER_ENDING}"
}

{ # Variables for WebSVN and SVN
  NAME_SVN_IMAGE="novatechweb/svn"
  NAME_SVN_CONTAINER="svn${CONTAINER_ENDING}"
  NAME_SVN_REPO_DV="DV_svn_repo${CONTAINER_ENDING}"
  SVN=172.16.0.101:443
  SVN_OPEN=172.16.0.101:80
  HOST_SVN_BACKUP_DIR=${BACKUP_DIR}/SVN
  SVN_REPOS=("ddio" "novatech" "NCD_Release")
}

{ # variables for GIT
  NAME_GIT_IMAGE="novatechweb/git"
  NAME_GIT_CONTAINER="git${CONTAINER_ENDING}"
  NAME_GIT_REPO_DV="DV_git_repo${CONTAINER_ENDING}"
  GIT=172.16.0.102:443
  GIT_OPEN=172.16.0.102:80
  HOST_GIT_BACKUP_DIR=${BACKUP_DIR}/GIT
}

{ # variables for MediaWIKI
  NAME_WIKI_IMAGE="novatechweb/wiki"
  NAME_WIKI_CONTAINER="wiki${CONTAINER_ENDING}"
  NAME_WIKI_MYSQL_CONTAINER="wiki_mysql${CONTAINER_ENDING}"
  NAME_WIKI_DV="DV_wiki${CONTAINER_ENDING}"
  NAME_WIKI_MYSQL_DV="DV_wiki_mysql${CONTAINER_ENDING}"
  MEDIAWIKI=172.16.0.103:443
  MEDIAWIKI_OPEN=172.16.0.103:80
  HOST_MEDIAWIKI_BACKUP_DIR=${BACKUP_DIR}/WIKI
  WIKI_MYSQL_PASSWORD=database-root-user-secret-pw
  MEDIAWIKI_USER=novatech
  MEDIAWIKI_PASSWORD=novatech
}

{ # variables for PHPMyAdmin
  NAME_PHPMYADMIN_CONTAINER="phpmyadmin${CONTAINER_ENDING}"
  NAME_PHPMYADMIN_MYSQL_CONTAINER="phpmyadmin_mysql${CONTAINER_ENDING}"
  NAME_PHPMYADMIN_MYSQL_DV="DV_phpmyadmin_mysql${CONTAINER_ENDING}"
  PHPMYADMIN=172.16.0.109:443
  PHPMYADMIN_OPEN=172.16.0.109:80
  PHPMYADMIN_PMA_SECRET="opGKy8P*FXJKZVqWuom6Bi8c8fgK1yaRDnq4loQ95g"
  PHPMYADMIN_MYSQL_PASSWORD=database-root-user-secret-pw
  PHPMYADMIN_PMA_USERNAME=novatech
  PHPMYADMIN_PMA_PASSWD=novatech
}

{ # variables for OpenLDAP
  NAME_LDAP_IMAGE="novatechweb/ldap"
  NAME_LDAP_CONTAINER="ldap${CONTAINER_ENDING}"
  NAME_LDAP_DV="DV_ldap${CONTAINER_ENDING}"
  OPENLDAP=172.16.0.110:389
  OPENLDAP_SECURE=172.16.0.110:636
  HOST_OPENLDAP_BACKUP_DIR=${BACKUP_DIR}/LDAP
}

{ # variables for Django
  NAME_DJANGO_IMAGE="novatechweb/django"
  NAME_DJANGO_CONTAINER="django${CONTAINER_ENDING}"
  DJANGO=172.16.0.110:80
  DJANGO_SECURE=172.16.0.110:443
  HOST_DJANGO_BACKUP_DIR=${BACKUP_DIR}/Django
  HOST_DJANGO_SRC_DIR=${BACKUP_DIR}/Django/code
}
