# Variables for WebSVN and SVN
SVN_IP=172.16.0.101
HOST_SVN_BACKUP_DIR=$(pwd)/BACKUP/SVN/
SVN_REPOS=("ddio" "novatech" "NCD_Release")

# variables for GIT
GIT_IP=172.16.0.102
HOST_GIT_BACKUP_DIR=$(pwd)/BACKUP/GIT/

# variables for MediaWIKI
MEDIAWIKI_IP=172.16.0.104
HOST_MEDIAWIKI_BACKUP_DIR=$(pwd)/BACKUP/WIKI/

# variables for OpenLDAP
OPENLDAP_IP=172.16.0.105
HOST_OPENLDAP_BACKUP_DIR=$(pwd)/BACKUP/LDAP/


#DJANGO_IP=172.16.0.104
#HOST_DJANGO_DIR=$(pwd)/code
#HOST_WEBSVN_PASSWD_DIR=$(pwd)/data/websvn_password
