#
# SVN Docker container
#
# Version 0.0

FROM image_svn:latest
MAINTAINER Joseph Lutz <Joseph.Lutz@novatechweb.com>

# create the volumes that will be needed
VOLUME ["/etc/htpasswd/", "/etc/apache2/ssl"]

CMD ["true"]
