#
# WebSVN Docker container
#
# Version 0.0

FROM image_websvn:latest
MAINTAINER Joseph Lutz <Joseph.Lutz@novatechweb.com>

# create the volumes that will be needed
VOLUME ["/etc/apache2/websvn_password/"]

CMD ["true"]
